name: sigma_esxcli_syslog_config_change
mode: alert
eval: |
  (
    e.process_name == "esxcli" && (e.process_args.contains("system") && e.process_args.contains("syslog") && e.process_args.contains("config")) && e.process_args.contains(" set")
  )

tests:
  - cleartext: "esxcli syslog config"
    process_name: esxcli
    process_args: "esxcli system syslog config set --loghost=192.168.1.1"
    should_match: true
  - cleartext: "normal ls"
    process_name: ls
    process_args: "ls -la"
    should_match: false
